### PR TITLE
import SequenceGenerator on all sql based database types

### LINKED ISSUE #321: import javax.persistence.SequenceGenerator is missing on User.kt
## Overview of the issue
A fresh generated project will fail on compile and throw following error:
```
error: incompatible types: NonExistentClass cannot be converted to Annotation
```

## KHipster Version(s)
1.14.0
-   [] Checking this box is mandatory (this is just to show you read everything)

In Case others also facing the error, apply the following to solve:
Add
```
import javax.persistence.SequenceGenerator
```
in Uesr.kt

### PR DESCRIPTION
**Pull request by emilpaw**
Fixes #321

### CODE REVIEW

File: generators/server/templates/src/main/kotlin/package/domain/User.kt.ejs [hunk 1]
```diff
@@ -87,9 +87,7 @@ import javax.persistence.JoinColumn
 import javax.persistence.JoinTable
 import javax.persistence.ManyToMany
 import javax.persistence.OneToMany
-    <%_ if (!(prodDatabaseType === 'mysql' || prodDatabaseType === 'mariadb')) { _%>
 import javax.persistence.SequenceGenerator
```
Comment (sendilkumarn) [inline generators/server/templates/src/main/kotlin/package/domain/User.kt.ejs:90]: Instead of this can we do `import java.persistence.*`  just like the main generator? @emilpaw  what do you think?

Comment (emilpaw) [reply generators/server/templates/src/main/kotlin/package/domain/User.kt.ejs:90]: We could do that but isn't the goal to get rid of the wildcard imports? Both detekt and ktlint don't allow wildcard imports in the default config.

Comment (sendilkumarn) [reply generators/server/templates/src/main/kotlin/package/domain/User.kt.ejs:90]: We do have a few, but didn't Kotlin relaxed the rule for wild card imports? I thought they did but I am not sure either. Lets have it like this itself then.

**Review by sendilkumarn — APPROVED** [review]

File: generators/server/templates/src/main/kotlin/package/domain/User.kt.ejs (hunk 1 above)
Comment (emilpaw) [reply generators/server/templates/src/main/kotlin/package/domain/User.kt.ejs:90]: AFAIK no. Removing the wildcard imports is also specified here: [!306](https://github.com/jhipster/jhipster-kotlin/issues/306) 

I generally think it's a good idea to get rid of them.

**Comment by sendilkumarn** [comment]
Thanks @emilpaw  let me merge this.
